# Generated by Django 5.0 on 2024-01-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_slugproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='post',
            new_name='product',
        ),
    ]
