// Authentication
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
// Account Activation
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
//Cargador
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// Logout
export const LOGOUT = 'LOGOUT';
// Reset Password
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';



// User Profile ****************************************** Obtener el perfil y actualizarlo
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';


// Store Categories  *************************************************
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING';
export const REMOVE_CATEGORY_LOADING = 'REMOVE_CATEGORY_LOADING';

// Stores ******************************************************
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';
export const GET_STORES_FAIL = 'GET_STORES_FAIL';

export const GET_STORE_LIST_CATEGORIES_SUCCESS = 'GET_STORE_LIST_CATEGORIES_SUCCESS';
export const GET_STORE_LIST_CATEGORIES_FAIL = 'GET_STORE_LIST_CATEGORIES_FAIL';

export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';
export const GET_STORE_FAIL = 'GET_STORE_FAIL';

export const RELATED_STORES_SUCCESS = 'RELATED_STORES_SUCCESS';
export const RELATED_STORES_FAIL = 'RELATED_STORES_FAIL';

export const SEARCH_STORES_SUCCESS = 'SEARCH_STORES_SUCCESS';
export const SEARCH_STORES_FAIL = 'SEARCH_STORES_FAIL';

export const GET_STORES_BY_ARRIVAL_SUCCESS = 'GET_STORES_BY_ARRIVAL_SUCCESS';
export const GET_STORES_BY_ARRIVAL_FAIL = 'GET_STORES_BY_ARRIVAL_FAIL';

export const SET_STORE_LOADING = 'SET_STORE_LOADING';
export const REMOVE_STORE_LOADING = 'REMOVE_STORE_LOADING';


export const GET_STORES_BY_SOLD_SUCCESS = 'GET_STORES_BY_SOLD_SUCCESS';
export const GET_STORES_BY_SOLD_FAIL = 'GET_STORES_BY_SOLD_FAIL';

export const FILTER_STORES_SUCCESS = 'FILTER_STORES_SUCCESS';
export const FILTER_STORES_FAIL = 'FILTER_STORES_FAIL';

// products ******************************************************
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const REMOVE_PRODUCTS_LOADING = 'REMOVE_PRODUCTS_LOADING';

